apiVersion: v1
data:
    foo: ENC[AES256_GCM,data:lViLsQ==,iv:tInTG34H73ZCGt8i+ryBEesSsTQ26mA5KIsx66YfFYU=,tag:ytmzsKuV2KsLGMccs0WkZw==,type:str]
kind: Secret
metadata:
    name: mysecret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1snr5hujp9ve058m99uwtm47s4jn5m3dsvy22k2eckxxpnxv2pays0kngq7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTGVBc2JRQ09qOUZNRmdr
            ZHZvaVR2dGY4eVNxb3lHTGxuUURLclhaWkcwCjAvNXhHRlYwYW1jdllaMXp0M0ZE
            ejdMVElJV3pFaldvTlg1cms3MDdhaDAKLS0tIFhxN3AxSE5rblU2cmxJNm9hVm5N
            NkN1cjdCTmJNcVZrUEtueEx5Q0JyU2MKFZRo/io/FoZVYX+WYRiZWi6TWcgrQ5+e
            3p35fvV+fjqc7MXeE0B6hdgFTKv4Tz1JkPsVVaDdNZpXHHWSITlNtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T09:39:38Z"
    mac: ENC[AES256_GCM,data:CVuk4j8hqA2woLrGpgQS5bPHKVB20yiWjmnC0qlijhFCVSnYTqt7W5T4ovBoKJmltFdmyZGTYw9tt5UxhUH1TBv4g8UR+wtti6wlXZLpYlpEwlXa9bN5yQwCndjVvQI9sP1vTpvGevL3lJAP/wYWxluXydMDBPvB9J4lCoslYLY=,iv:RnRx8Dk0C5FoaHLQaMnS6lN6umqQyBU5c2vGusQZgCU=,tag:0fmrSjmJ+4SXF99KsDGEwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
