---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./clusters/my-cluster/sops
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: sops
  targetNamespace: default
  timeout: 2m0s
  wait: true
