apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 60m
  path: ./clusters/my-cluster/sops
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
