apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops
  namespace: sops
spec:
  interval: 60m0s # detect drift and undo kubectl edits every hour
  wait: true # wait for all applied resources to become ready
  timeout: 3m0s # give up waiting after three minutes
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true # remove stale resources from cluster
  force: false # enable this to recreate resources on immutable fields changes
  targetNamespace: sops # set the namespace for all resources
  sourceRef:
    kind: GitRepository
    name: sops
  interval: 60m
  path: "./apps/base/sops"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
